### PR TITLE
wip: Pre-Record Hook

### PR DESCRIPTION
**Pull request by hansjhoffman**
Possible ways to solve Issue #122. Basically add some sort of "before" life cycle "ish" method to the `recordHook` fn to **inject** data into the mapping fn so we don't have user code running unnecessarily _n_ number of times. 

## Approach 1

Current approach in this PR. Uses a generic type so implementer can type incoming data. Avoids a breaking change.

```ts
  listener.use(
    recordHook(
      "Contact",
      <Extra>(record: FlatfileRecord, _event: FlatfileEvent, extra: Extra) => {
        console.log("extra: " + JSON.stringify(extra, null, 2));

        const firstName = record.get("firstName");

        if (typeof firstName === "string") {
          record.set("firstName", firstName.toUpperCase());
        }

        return record;
      },
      <Extra>(): Extra => {
        return { foo: "bar" } as Extra;
      },
    ),
  );
```

## Approach 2

Closer to the Jest approach I was thinking. Avoids having a bunch of optional fn params but introduces a breaking change

```ts
  listener.use(
    recordHook("Contact", {
      setup: (_event: FlatfileEvent): Extra => {
        return { foo: "bar" } as Extra;
      },
      map: (record: FlatfileRecord, _event: FlatfileEvent, extra: Extra) => {
        console.log("extra: " + JSON.stringify(extra, null, 2));

        const firstName = record.get("firstName");

        if (typeof firstName === "string") {
          record.set("firstName", firstName.toUpperCase());
        }

        return record;
      },
    }),
  );
```

## Approach 3

Using globals like Jest

```ts
  listener.use(
    recordHook("Contact", () => {
      setup((_event: FlatfileEvent): Extra {
        return { foo: "bar" } as Extra;
      });

      map((record: FlatfileRecord, _event: FlatfileEvent, extra: Extra) => {
        console.log("extra: " + JSON.stringify(extra, null, 2));

        const firstName = record.get("firstName");

        if (typeof firstName === "string") {
          record.set("firstName", firstName.toUpperCase());
        }

        return record;
      });
  }),
);
```

### CODE REVIEW

**Comment by dboskovic** [comment]
what about just `use(bulkRecordHook((records) => {})`

**Comment by ashleygmulligan2** [comment]
@carlbrugger will provide feedback

**Comment by ashleygmulligan2** [comment]
The problem he's solving is he needs a call to allow for custom functions that operate once per "commit".

**Comment by carlbrugger** [comment]
Closed with https://github.com/FlatFilers/flatfile-plugins/pull/162

**Pull request closed without merging**
