### PR TITLE
fix: add mode filter on XLSX extractor

### PR DESCRIPTION
**Pull request by bigcountrycrane**
Right now the XLSX extractor will look for all "files:created", but you can create a file in "export" mode now as well as "import". This scopes the extractor down to the "import" mode so you don't get in an endless loop.

### CODE REVIEW

**Comment by ashleygmulligan2** [comment]
Nice, next time - when you make a change, run `npm run changeset `to up the version, and update the version number in the package.json file for the plugin too. Before approving I will test this, so give me til tomorrow to merge.

**Comment by bigcountrycrane** [comment]
The original approach actually won't work, because `mode` isn't reported on the event. It's only part of a `file` object where we then specify the `mode` as either `import` or `export`

-> My event listener received an event: "file:created"
{
  "_accessToken": "sk_1EAzZ6UiekiFKAPy9ZP26Ppje49Li2w6",
  "_apiUrl": "https://platform.flatfile.run/api",
  "src": {
    "id": "stg_evt_Z3wIz3xeXT35Kc8q",
    "domain": "file",
    "topic": "file:created",
    "context": {
      "fileId": "stg_fl_qMn2gBIT",
      "actorId": "stg_usr_Awu9p7L1",
      "spaceId": "stg_sp_qOxIWVs8",
      "accountId": "stg_acc_5gdfdI14",
      "environmentId": "stg_env_mxQgdwCX"
    },
    "payload": {},
    "callbackUrl": "",
    "dataUrl": "",
    "createdAt": "2023-06-28T20:51:39.629Z",
    "acknowledgedAt": null,
    "origin": null,
    "namespaces": []
  },
  "afterAllCallbacks": {},
  "cache": {
    "eventCache": {}
  },
  "domain": "file",
  "topic": "file:created",
  "context": {
    "fileId": "stg_fl_qMn2gBIT",
    "actorId": "stg_usr_Awu9p7L1",
    "spaceId": "stg_sp_qOxIWVs8",
    "accountId": "stg_acc_5gdfdI14",
    "environmentId": "stg_env_mxQgdwCX"
  },
  "payload": {},
  "target": "",
  "origin": {},
  "action": "",
  "namespace": []
}

To make this work, I updated the excel.extractor.ts file to return false if the file.mode !== "import". Also, I noticed that the File_ definition in typescript doesn't have the "mode" parameter on it, even though that's available when I get a file. Guessing that should be added into wherever we do our TS definitions.

**Comment by ashleygmulligan2** [comment]
question @bigcountrycrane why do you have a "xlsx extractor copy" folder?

**Comment by bigcountrycrane** [comment]
@ashleygmulligan2 good catch. I forgot to switch branches when I started on something else. Just committed an update to remove the copy

**Comment by hansjhoffman** [comment]
@ashleygmulligan2 Just ran into this issue during our dry run for the webinar. This bug is conflicting with our "Excel Workbook Export" plugin so it would be nice to get this merged ASAP. What else needs to be done?

**Review by dboskovic — APPROVED** [review]

**Pull request merged**
