### PR TITLE
feat: add optional api parameter to job handler plugin

### PR DESCRIPTION
**Pull request by tnc1997**
## Please explain how to summarize this PR for the Changelog:
This change adds an optional `api` parameter to the job handler plugin in order to support regional data centres.

## Tell code reviewer how and what to test:
The job handler plugin should be tested to ensure that it works with the default client and a regional specific client.

### CODE REVIEW

**Comment by carlbrugger** [comment]
Hi @tnc1997, thanks for contributing! 

After taking a look at your PR, I don't believe this change is necessary. `FlatfileClient` has the smarts to get the appropriate API url (you can [take a look at the code here](https://github.com/FlatFilers/flatfile-node/blob/main/src/wrapper/FlatfileClient.ts#L47)). All you need to do is set the `FLATFILE_API_URL` env var with the appropriate regional API url: `FLATFILE_API_URL=https://platform.flatfile.com/api`.

**Comment by tnc1997** [comment]
Hi @carlbrugger, could you provide a link to the docs or a sample so that we can configure this in our React application?

**Comment by carlbrugger** [comment]
@tnc1997 this should have the information you're looking for https://flatfile.com/docs/developer-tools/deploying#configuring-the-api-url-for-deployment

**Comment by tnc1997** [comment]
Hi @carlbrugger, we have followed the "Embedding with a Specific API URL" instructions and the "API Interaction with a Specified Environment" instructions, however we do not have anything to deploy as we are not self-hosting.

> npx flatfile@latest deploy

**Comment by carlbrugger** [comment]
Gotcha. If you're running the listener like that, you can pass the `apiUrl` to the `FlatfileProvider` like so:
```
<FlatfileProvider
      accessToken={ACCESS_TOKEN}
      apiUrl="https://platform.uk.flatfile.com/api"
    >
  <App />
</FlatfileProvider>
```

**Comment by tnc1997** [comment]
Hi @carlbrugger, this is what we are doing, but the `FlatfileClient` in the plugin defaults to the US API URL:

```typescript
const apiUrl = useFlatfileApiUrl();

const publishableKey = useFlatfilePublishableKey();

const spaceUrl = useFlatfileSpaceUrl();

return (
	<FlatfileFlatfileProvider apiUrl={apiUrl} config={{ spaceUrl }} publishableKey={publishableKey}>
		{children}
	</FlatfileFlatfileProvider>
);
```

**Comment by carlbrugger** [comment]
@tnc1997 ah, I see the issue. We'll create a ticket and get a solution out for you.

**Comment by carlbrugger** [comment]
@tnc1997 this issue should be resolved by installing `@flatfile/api@1.9.19`. We fixed an issue passing the api url.

**Pull request closed without merging**
