### PR TITLE
Adds a new JSON multi-sheet extractor plugin

### PR DESCRIPTION
**Pull request by amarbakir**
## Please explain how to summarize this PR for the Changelog:
* Initialize JSON multi-sheet extractor plugin
* Refactor out shared code from plugins/json-extractor into utils/extractor
* Add utils/extractor tests
* Simplify JSON extractor/multisheet extractor test cases based on core extraction logic now living in utils/extractor
* Add example of Array and primitive (int) parsing to unit test

## Tell code reviewer how and what to test:
The `plugins/json-extractor` and `plugins/json-multisheet-extractor` plugins. Existing behavior should not have been changed

Requirements:
* Must allow users to upload a single JSON file which results in data correctly uploading to the corresponding sheets
* Should be able to determine sheet to data relationships through top level JSON keys. E.g.
```json
{
	"contacts": [ // sheet 1
		{ // record 1
			"firstName": "John", // header 1, value
            		"lastName": "Doe", // header 2, value
            		"email": "john.doe@example.com"
		},
		{ // record 2
			"firstName": "Jane", // header 1, value
        			"lastName": "Smith",
        			"email": "jane.smith@example.com"
		},
	],
	"orders": [ // sheet 2
		{ // record 1
			"id": "ORD123456", // header 1, value
            		"amount": 250 // header 2, value
		},
	]
}
```

Resulting UI somewhat supports this, but a nice next step would be to allow for a multisheet import in one step through the UI, or at the very least not require one to go back to the files list to reimport the second sheet (load data from sheet `contacts` -> import data to `contacts` & load data from sheet `order` -> import data to `order` all in one step):
Screenshot 2024-10-30 at 6 32 43 PM

As part of this effort, we surfaced this issue that has now been resolved: https://github.com/FlatFilers/flatfile-plugins/issues/695

### CODE REVIEW

**Comment by amarbakir** [comment]
@carlbrugger I think we're ready for a review whenever you are! Let us know how you prefer to handle the AI review bot's suggestions. Some are already addressed here: https://github.com/aprimetechnology/flatfile-plugins/pull/1

Thanks!

**Comment by carlbrugger** [comment]
@amarbakir thanks for the PR! I will look it over.

**Comment by carlbrugger** [comment]
@amarbakir I really like the feature you're adding here. 🙌🏼  I integrated this functionality into the existing JSON extractor plugin. Would you take a look at https://github.com/FlatFilers/flatfile-plugins/pull/698?

**Comment by amarbakir** [comment]
Hey @carlbrugger ! Just seeing your comments. I just took a look now and it's super straightforward. Overall I'm a fan of having this as an extra function of the existing extractor

Working on Slack access now! I should be able to get that through APrime soon

**Comment by carlbrugger** [comment]
Awesome! We'll get https://github.com/FlatFilers/flatfile-plugins/pull/698 released in short order so you can start using it. Thanks for your contribution!

**Comment by amarbakir** [comment]
Functionality added through https://github.com/FlatFilers/flatfile-plugins/pull/698

**Pull request closed without merging**
